INSERT INTO `progra`.`category` (`category`) VALUES 
("PlayStation 4"),
("Computers and Accessories"),
("Music"),
("Electronics"),
("Movies and TV Shows"),
("Movies"),
("Accessories"),
("Sports, Fitness and Outdoors"),
("Luggage and Bags"),
("Games"),
("Action and Adventure"),
("Women"),
("Accounting and Finance"),
("Accessories"),
("Bath and Shower"),
("Business Accounting"),
("Bedroom Furniture"),
("Personal Finance"),
("Action and Toy Figures"),
("Shoes and Handbags"),
("Kindle Store"),
("Accessories"),
("Shoes"),
("Baby"),
("Clothing and Accessories"),
("Women''s Shoes"),
("Bendables"),
("Kindle eBooks"),
("Bedroom Wardrobes"),
("Beds, Frames and Bases"),
("Antivirus and Security"),
("Bath Additives"),
("Antivirus"),
("Watch Boxes"),
("Watchbands"),
("Earrings"),
("Accessories"),
("Bags and Backpacks"),
("Arts, Film and Photography"),
("Sports Sunglasses"),
("Consoles"),
("Blank Media"),
("Accessories"),
("Office Products"),
("Bath and Body"),
("BD-R"),
("Batteries and Chargers"),
("TV Shows"),
("Cables and Adapters"),
("Accessories and Peripherals"),
("Alternative and Indie"),
("Cases and Storage"),
("Bhangra"),
("Lawn and Garden"),
("Blues"),
("Bath Additives"),
("Comedy and Spoken Word"),
("Art and Craft Supplies"),
("BD-RE"),
("Architecture"),
("CD-R"),
("Cinema and Broadcast"),
("Water Bottles and Shakers"),
("Backpacks"),
("Necklaces"),
("Men"),
("Bangles and Bracelets"),
("Bath Bombs"),
("Security Suites"),
("Bedside Tables"),
("Action and Adventure"),
("Ballerinas"),
("Bobbleheads"),
("Women"),
("Playsets"),
("Activity and Play Time"),
("Props and Replicas"),
("Western Wear"),
("Door Bouncers"),
("Boots"),
("Arts, Film and Photography"),
("Dressers and Chests of Drawers"),
("Business and Office"),
("Dressing Tables"),
("Bath Pearls and Flakes"),
("Rings"),
("Women"),
("Casual Backpacks"),
("Archery"),
("Dance"),
("CD-RW"),
("Adhesives"),
("Bath Bombs"),
("Country"),
("Categories"),
("Adapters"),
("Audio and Video Accessories"),
("Controllers"),
("Backyard Birding Supplies"),
("Dance and Electronic"),
("Bath Pearls and Flakes"),
("Adhesive Sheets"),
("Arrows and Bolts"),
("DVD+R"),
("Design and Fashion"),
("DVD+RW"),
("Rucksacks"),
("Boys"),
("Pendants"),
("Bubble Bath"),
("Business Tools Training"),
("Mattresses and Box Springs"),
("Architecture"),
("Tops, Tees and Shirts"),
("Casual Shoes"),
("Playmats and Floor Gyms"),
("Statues, Maquettes and Busts"),
("Polos"),
("Cinema and Broadcast"),
("Garden and Outdoor Furniture"),
("Communication"),
("Bath Salts"),
("Precious Coins and Bars"),
("Bath Oils"),
("Girls"),
("Laptop Backpacks"),
("DVD-R"),
("Crossbow Bolts"),
("History, Theory and Criticism"),
("Adhesive Sprays"),
("Bubble Bath"),
("Devotional and Spiritual"),
("Bath Salts"),
("Bird Feeders"),
("Bath Oils"),
("PC Headsets"),
("Headsets"),
("Tub Tea"),
("Skins"),
("Bird Food"),
("Easy Listening"),
("Adhesive Waxing"),
("Film Songs"),
("Museums and Museology"),
("Targeting Arrows"),
("DVD-RAM"),
("Nappy Backpacks"),
("Home and Kitchen"),
("Tub Tea"),
("Voice Recognition"),
("Bathing Accessories"),
("Jewellery Sets"),
("Hammocks, Swing Chairs and Accessories"),
("Bath Brushes"),
("Dance"),
("Loofahs"),
("Shirts"),
("Toy Figures"),
("Boat Shoes"),
("Swings, Bouncers and Rockers"),
("Tees"),
("Loafers and Moccasins"),
("Arts and Crafts"),
("Shower Caps"),
("Design and Fashion"),
("Hammocks"),
("History, Theory and Criticism"),
("Swing Chairs"),
("Museums and Museology"),
("Mangalsutras and Tanmaniyas"),
("Music"),
("Backyard Birding Supplies"),
("Office Suites"),
("Bag Organizers"),
("DVD-RW"),
("Briefcases"),
("Bow Slings"),
("Music"),
("Bows"),
("Painting"),
("Folk and Songwriter"),
("Art Glues"),
("Indian Folk"),
("Art Pastes"),
("Ghazals"),
("Gospel"),
("Hard Rock and Metal"),
("Healing and Meditation"),
("Birdbaths"),
("Thumb Grips"),
("Bathing Accessories"),
("PC Microphones"),
("Xbox One"),
("Barbecue and Outdoor Dining"),
("Games"),
("PC Speakers"),
("Webcams"),
("Holiday and Religious"),
("Blank Media"),
("Arts and Crafts Tape"),
("Basic Bows"),
("Photography"),
("Fabric Adhesives"),
("Canvas and Beach Tote Bags"),
("Mini DVD"),
("Voice Recognition"),
("Bird Feeders"),
("Mangalsutras"),
("Children''s Software"),
("Painting"),
("Patio Benches and Stools"),
("Aprons and Smocks"),
("Sponges"),
("Sneakers"),
("Jumpers"),
("Clogs"),
("Tank Tops"),
("Bath Sets and Kits"),
("Blackboards and Whiteboards"),
("Patio Chairs"),
("Early Learning"),
("Photography"),
("Tanmaniyas"),
("Bird Food"),
("Camera and Photo Accessories"),
("Coin Purses and Pouches"),
("Sculpture"),
("Glue Sticks and Pens"),
("Gym Bags"),
("Compound Bows"),
("BD-R"),
("Christian Pop and Rock"),
("Barbecue and Smoker Accessories"),
("Consoles"),
("Bath Brushes"),
("Christmas Music"),
("BD-RE"),
("Loofahs"),
("Crossbows"),
("Laptop Bags"),
("Hot Glue Sticks"),
("Batteries and Chargers"),
("Theatre and Spectacles"),
("Birdbaths"),
("Folding Chairs"),
("Nose Rings and Pins"),
("Rocking Chairs"),
("Theatre and Spectacles"),
("Rattan, Bamboo, Casted and Moulded Chairs"),
("Mathematics"),
("Clay and Dough"),
("Body Scrubs"),
("Tops"),
("Colouring Books and Pads"),
("Ethnic Footwear"),
("Swings"),
("Dresses"),
("Body Washes"),
("Reading and Language"),
("Patio Furniture Sets"),
("Biographies, Diaries and True Accounts"),
("Nose Pins"),
("Adapters"),
("Barbecue and Outdoor Dining"),
("Biographies, Diaries and True Accounts"),
("Biographies and Autobiographies"),
("Laptop Backpacks"),
("Barbecue and Smoker Accessories"),
("Biographies and Autobiographies"),
("Mounting Adhesive Systems"),
("Longbows"),
("Diaries, Letters and Journals"),
("Barbecue Aprons"),
("Shower Caps"),
("CD-R"),
("Barbecue Brushes"),
("Sponges"),
("Indi Pop"),
("Barbecue Cleaning Products"),
("Barbecue Aprons"),
("Accessories"),
("Barbecue Brushes"),
("Barbecue Cooking Grates"),
("Indian Classical"),
("Bath Sets and Kits"),
("Barbecue Cookware"),
("CD-RW"),
("Body Scrubs"),
("Carnatic Instrumental"),
("True Accounts"),
("Recurve Bows"),
("Boards"),
("Laptop Briefcases"),
("Diaries, Letters and Journals"),
("Batteries"),
("Laptop Messenger Bags"),
("Nose Rings"),
("Patio Sofas"),
("Body Wash Gels"),
("Education and Reference"),
("Trousers"),
("Toddler Toys"),
("Fashion Sandals"),
("Craft Kits"),
("Arts"),
("Body Wash Oils"),
("Patio Umbrellas, Canopies and Shade"),
("Deodorants and Antiperspirants"),
("Hair Jewellery"),
("Camcorder Batteries"),
("Soaps"),
("Laptop Roller Cases"),
("Camera Batteries"),
("Beauty Tools and Accessories"),
("Messenger Bags"),
("True Accounts"),
("Clayboard"),
("Bowstrings"),
("Business and Economics"),
("Carnatic Vocal"),
("Barbecue Griddles"),
("Body Washes"),
("Hindustani Instrumental"),
("Pizza Barbecue Stones"),
("DVD+R"),
("Batteries and Chargers"),
("Body Wash Gels"),
("DVD+RW"),
("Barbecue Cleaning Products"),
("Cables and Adapters"),
("Barbecue Grids"),
("Hindustani Vocal"),
("Business Self-Help"),
("Cocking Devices"),
("Gessoboard"),
("Bags and Cases"),
("Crossbow Scopes"),
("Business and Economics"),
("Finger Tabs"),
("Cosmetic Bags"),
("Nappy Bags"),
("Business, Strategy and Management"),
("Battery Chargers"),
("School Bags"),
("Economics"),
("Calibration Charts and Grey Cards"),
("Bands"),
("Canopies"),
("Beads"),
("Activity Play Centres"),
("Business and Professional"),
("Casual Trousers"),
("Fashion Slippers"),
("Encyclopedias"),
("Children''s Knitting and Textile Design"),
("Patio Umbrellas"),
("Clips"),
("Colour Calibration Charts"),
("Industries and Business Sectors"),
("Waist Bags"),
("Make-Up Pouches"),
("Fletches"),
("Belts"),
("Hardboard"),
("Business, Strategy and Management"),
("Jazz"),
("Barbecue Mitts"),
("Cases and Protectors"),
("Barbecue Cooking Grates"),
("DVD-R"),
("Body Wash Oils"),
("Barbecue Cookware"),
("Controllers"),
("Barbecue Thermometers"),
("Kids'' Music and Radio Plays"),
("Men''s Belts"),
("Economics"),
("Pastelboard"),
("Kisser Buttons"),
("Refillable Containers"),
("Calendars"),
("Nocks"),
("Toiletry Kits and Bags"),
("Grey Cards"),
("Combs"),
("Sunloungers"),
("Children''s Weaving"),
("Exam Preparation"),
("Flip-Flops and House Slippers"),
("Formal Trousers"),
("Baby Toys"),
("Floaters and Sports Sandals"),
("Banking and Insurance"),
("Formal Shoes"),
("Fake Food Makers"),
("Tables"),
("Pumps"),
("Pins"),
("Patio Coffee Tables"),
("Lens Calibration Charts"),
("Train Cases"),
("Protective Gear"),
("Banks and Banking"),
("Children and Young Adults"),
("Commerce"),
("Commercial Policy"),
("Adventure"),
("Comparative"),
("Comics and Mangas"),
("Crafts, Hobbies and Practical Interests"),
("Bathing Accessories"),
("Wood Art Boards"),
("Canvas"),
("Banner and Sign Cloth"),
("Canvas Pads"),
("Canvas Panels"),
("Canvas Tools and Accessories"),
("Bath Brushes"),
("Pre-Stretched Canvas"),
("Loofahs"),
("Rolled Canvas"),
("Children''s Music"),
("Women''s Belts"),
("Cutting Tools"),
("Barbecue Utensils"),
("Handbags and Clutches"),
("Art Blades"),
("Barbecue Skewers"),
("Barbecue Griddles"),
("Skins"),
("Deodorants and Antiperspirants"),
("DVD-RAM"),
("Soaps"),
("DVD-RW"),
("Fragrance"),
("Floppy Disks"),
("Pizza Barbecue Stones"),
("Thumb Grips"),
("Barbecue Tongs"),
("Barbecue Grids"),
("Backpack Handbags"),
("Art Knives"),
("Children''s Classical Music"),
("Shower Caps"),
("Radio Plays"),
("Crime and Thriller"),
("Development and Growth"),
("Quivers"),
("Camcorder and Video Accessories"),
("Patio Dining Tables"),
("Targets"),
("Patio Side Tables"),
("Tiaras"),
("Sport Shoes"),
("Glass Arts and Sun Catchers"),
("Defence"),
("Jewellery"),
("Baby Balls"),
("Paint by Number Kits"),
("Jeans"),
("Painting Craft Kits"),
("Mirrors"),
("Engineering Entrance"),
("Music Boxes"),
("Bowling Shoes"),
("Rattles and Plush Rings"),
("Accessories"),
("Stroller Toys"),
("Picnic Tables"),
("Hallway Furniture"),
("Badminton"),
("Camcorder Batteries"),
("Econometrics"),
("Chargers"),
("Economic Conditions"),
("Early Learning"),
("Lounge and Fusion"),
("Sponges"),
("Cutting Rails"),
("Clutches"),
("Barbecue Turners"),
("Barbecue Mitts"),
("Barbecues"),
("PlayStation 3"),
("Beekeeping Equipment"),
("Deodrants and Roll-ons"),
("Mini DVD"),
("Eau de Toilette"),
("Bee Protective Gear"),
("Games"),
("Barbecue Thermometers"),
("Beekeeping Tools"),
("Consoles"),
("Handbags"),
("Glass Cutting Tools"),
("Cotton and Swabs"),
("Pop"),
("Family, Personal and Social Issues"),
("RandB and Soul"),
("Economic History"),
("HDMI Cables"),
("Rabindra Sangeet"),
("Chest of Drawers"),
("Rap and Hip-Hop"),
("Complete Sets"),
("Key Cabinets"),
("Boxes and Organisers"),
("Bath Toys"),
("Dance Shoes"),
("Bricks and Blocks"),
("Armoires"),
("Football Shoes"),
("Counting Frames"),
("Exams by UPSC"),
("Paper Craft"),
("Leggings"),
("Finance and Accounting"),
("Hammering and Nailing Toys"),
("Boxes"),
("Golf Shoes"),
("Hobbyhorses"),
("Chests"),
("Mirrors"),
("Reggae"),
("Shoe Racks"),
("Equipment Bags"),
("Case and Bag Accessories"),
("Umbrella Holders"),
("Footwear"),
("Home Bar Furniture"),
("Belts and Harnesses"),
("Economic Policy and Development"),
("Men"),
("Environmental Economics"),
("Fantasy, Science Fiction and Horror"),
("Facial Steamers"),
("Mat Cutter Blades"),
("Foot Care"),
("Hobos and Shoulder Bags"),
("Accessories"),
("Messenger Bags"),
("Garden and Outdoor Furniture"),
("Barbecue Utensils"),
("Accessory Kits"),
("Batteries and Chargers"),
("Hammocks, Swing Chairs and Accessories"),
("Eau de Parfum"),
("Tapes"),
("Cables and Adapters"),
("Zip Media"),
("Hammocks"),
("Cables"),
("Barbecue Skewers"),
("Potlis and Wristlets"),
("Barbecue Tongs"),
("DVI Cables"),
("Callus Shavers"),
("Barbecue Turners"),
("DisplayPort Cables"),
("Barbecues"),
("Ethernet Cables"),
("Mat Cutters"),
("FDD Cables"),
("Fantasy"),
("Beekeeping Equipment"),
("Drawing"),
("Horror and Ghost Stories"),
("Free Enterprise"),
("Bee Protective Gear"),
("Nets"),
("Art Blenders"),
("Beekeeping Tools"),
("Art Horses"),
("Garden and Outdoor Furniture"),
("Belts"),
("Inflation"),
("Harnesses"),
("Bar Cabinets"),
("Art Paper"),
("Racquets"),
("Rock"),
("Racquet Grips"),
("Airbrush Paper"),
("Rolls"),
("Walking Shoes"),
("Towers"),
("Indoor Climbers and Play Structures"),
("Government Recruitment"),
("Coats and Jackets"),
("Sand Art"),
("Management Entrance"),
("Scratch Art"),
("Coats"),
("Motor Activity Toys"),
("Trays"),
("Outdoor Multisport Training Shoes"),
("Pull Along Toys"),
("Charcoal Paper"),
("Shuttlecocks"),
("Rocking and Spring Ride-Ons"),
("Sound Effects and Nature"),
("Soft Toys"),
("Cases and Bags"),
("Soundtracks and Musicals"),
("Binocular Cases"),
("Film Music"),
("Camcorder Cases"),
("Bar Sets"),
("Hammocks, Swing Chairs and Accessories"),
("Sorting, Stacking and Plugging Toys"),
("Interest"),
("Sound Toys"),
("Hammocks"),
("Science Fiction"),
("HDMI Cables"),
("Callus Stones"),
("Satchels"),
("Swing Chairs"),
("Foot Creams and Lotions"),
("Cases and Protectors"),
("Moisturizing Socks"),
("Controllers"),
("Scrubs"),
("Headsets"),
("Shoe Deodorant"),
("Memory Units and Harddrives"),
("Shoe Pads"),
("Skins"),
("Hair Combs, Wigs and Accessories"),
("Eau de Cologne"),
("Thumb Grips"),
("Patio Benches and Stools"),
("Xbox 360"),
("Sling and Cross-Body Bags"),
("IDE Cables"),
("Totes"),
("Games"),
("Games, Toys and Activities"),
("Swing Chairs"),
("Wallets"),
("Historical Fiction"),
("Patio Benches and Stools"),
("Consoles"),
("History"),
("Spinning and Battling Tops"),
("Humour"),
("Labor and Industrial Relations"),
("Teaching Clocks"),
("Camera and Camcorder Combination Bags"),
("Barstools"),
("Interactive and Activity Books"),
("Language Learning"),
("Literature and Fiction"),
("Wine Racks"),
("Classic Fiction"),
("Camera Backpacks"),
("Camera Cases"),
("Musicals"),
("Special Interest"),
("Sufi and Qawwali"),
("Western Classical"),
("Ballet and Dance"),
("Strings"),
("Walkers"),
("Drawing Paper"),
("Baseball"),
("Running Shoes"),
("Cleaning and Care"),
("Skateboarding Shoes"),
("Baseballs"),
("Pouches"),
("Gilets"),
("Bats"),
("Ring Cushions"),
("Batting Gloves"),
("Ring Sizers"),
("Newsprint Paper"),
("Wood"),
("Medical Entrance"),
("Tennis Shoes"),
("Doodle and Scribbler Boards"),
("Pastel Paper"),
("Drawing and Painting Supplies"),
("Track and Field Shoes"),
("Warranties"),
("Jackets"),
("Anklets"),
("Sweaters"),
("Body Jewellery"),
("Chalk"),
("Cardigans"),
("Kids Coloured Pencils"),
("Basketball"),
("Baby Care"),
("Ponchos and Capes"),
("Shrugs"),
("Backboard Accessories"),
("Pullovers"),
("Backboards"),
("Sweatshirts and Hoodies"),
("Basketballs"),
("Baby Grooming"),
("Macroeconomics"),
("Hoodies"),
("Air Pumps and Accessories"),
("Chamber Music"),
("Sweatshirts"),
("Opera and Vocal"),
("Drama"),
("Billiards"),
("Poetry"),
("Lens Cases"),
("Short Stories"),
("Lighting Cases"),
("Money and Jobs"),
("Microscope Cases"),
("Mysteries and Curiosities"),
("Telescope Cases"),
("Billiard Tables"),
("Kids'' Furniture"),
("Accessories"),
("Luggage"),
("Beds"),
("Patio Chairs"),
("Bookcases"),
("Briefcases"),
("Chairs"),
("Folding Chairs"),
("Children''s Luggage"),
("Rocking Chairs"),
("Bean Bags"),
("PS/2 Cables"),
("Luggage Cosmetic Cases"),
("Parallel Cables"),
("Patio Chairs"),
("RGB Cables"),
("Brushes"),
("Folding Chairs"),
("Braiders"),
("Rocking Chairs"),
("Perfume"),
("Combs"),
("Attar"),
("SAS Cables"),
("Body Sprays and Mists"),
("SCSI Cables"),
("Rattan, Bamboo, Casted and Moulded Chairs");